version: "3"

services:
  #MONGODB
  mongodb_client:
    container_name: mongodb_client
    image: mongo
    restart: always
    command: mongod --port 27020
    ports:
      - "27020:27020"
    networks:
      - auth-network
    volumes:
      - data:/data/db
  mongo_seed:
    image: mongo
    links:
      - mongodb_client
    volumes:
      - ../salon-container/mongo-seed:/mongo-seed
    command: /mongo-seed/import3.sh
    networks:
      - auth-network

  #MYSQL

  mysqlclient:
    container_name: mysqlclient
    build: "../salon-container/db_mysql"
    # ports:
    #   - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: service_salon
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - salon-network

  #AUTH SERVICE

  auth_client:
    container_name: auth_client
    depends_on:
      - mongodb_client
    build: "../salon-container/auth_service"
    environment:
      - browser_url=http://localhost:4060
      - DB_CONN=mongodb://mongodb_client:27020/cluster0
    ports:
      - "3020:3000"
    restart: always
    networks:
      - auth-network

  # SALON SERVICE

  salon_client:
    container_name: salon_client
    depends_on:
      - mysqlclient
    build: "../salon-container/salon_service"
    environment:
      - DB_HOST=mysqlclient
      - PORT=4010
    ports:
      - "4050:4010"
    restart: always
    networks:
      - salon-network
      - auth-network

  # BROWSER SERVICE

  browser_client:
    container_name: browser_client
    build: "../browser_service"
    depends_on:
      - auth_client
    environment:
      - salon_service_url=http://localhost:4050
      - auth_service_url=http://localhost:3020
    ports:
      - "4060:4030"
    networks:
      - auth-network
      - salon-network

  # TRANSPORT SERVICE

  transport_client:
    container_name: transport_client
    build: "../transport_service"
    environment:
      - salon_service_url=http://salon_client:4050
      - auth_service_url=http://auth_client:3020
    ports:
      - "5004:5001"
    networks:
      - auth-network
      - salon-network

  # FRONT

  front_client:
    container_name: front_client
    build: "."
    stdin_open: true
    ports:
      - "8085:8082"
    environment:
      - VUE_APP_AUTH_API=http://localhost:3020
      - VUE_APP_SALON_API=http://localhost:4050
      - VUE_APP_BROWSER_API=http://localhost:3020
      - VUE_APP_TRANSPORT_API=http://localhost:5004
    depends_on:
      - auth_client
      - salon_client
    networks:
      - auth-network
      - salon-network

networks:
  auth-network:
    driver: bridge
  salon-network:
    driver: bridge
volumes:
  db_data: {}
  data:
