version: "3"

services:
  #MONGODB
  mongodb:
    
    image: mongo
    restart: always
    # ports:
    #   - "27017:27017"
    networks:
      - auth-network
    volumes:
      - data:/data/db
  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command: /mongo-seed/import.sh
    networks:
      - auth-network

  #MYSQL

  mysql:
    container_name: mysql
    # image: mysql:5.7
    build: "./db_mysql"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: service_salon
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - salon-network

  #AUTH SERVICE

  auth:
    depends_on:
      - mongodb
    build: "./auth_service"
    environment:
      - browser_url=http://browser:4030
    ports:
      - "3000:3000"
    restart: always
    networks:
      - auth-network

  # SALON SERVICE

  salon:
    depends_on:
      - mysql
    build: "./salon_service"
    ports:
      - "4010:4010"
    restart: always
    networks:
      - salon-network

  # BROWSER SERVICE

  browser:
    build: "../browser_service"
    depends_on:
      - auth
    environment:
      - salon_service_url=http://salon:4010
      - auth_service_url=http://auth:3000
    ports:
      - "4030:4030"
    networks:
      - auth-network
      - salon-network

  # TRANSPORT SERVICE

  transport:
    build: "../transport_service"
    environment:
      - salon_service_url=http://salon:4010
      - auth_service_url=http://auth:3000
    ports:
      - "5001:5001"
    networks:
      - auth-network
      - salon-network

  # FRONT

  front:
    build: "./car-rental-vue"
    stdin_open: true
    ports:
      - "8081:8081"
    environment: 
      - VUE_APP_BROWSER_API=http://localhost:4030
      - VUE_APP_SALON_ID=600731d43526f63658f62f3b
    depends_on:
      - auth
      - salon
    networks:
      - auth-network2
      - salon-network2

      # ================ SALON 2 ==================

    #MONGODB

  mongodb2:
    image: mongo
    restart: always
    command: mongod --port 27018
    ports:
        - '27018:27018'
    networks:
      - auth-network2
    volumes:
      - data:/data/db2
  mongo_seed2:
    image: mongo
    links:
      - mongodb2
    volumes:
      - ./mongo-seed:/mongo-seed
    command: /mongo-seed/import2.sh
    networks:
      - auth-network2

  #MYSQL

  mysql2:
    container_name: mysql2
    # image: mysql:5.7
    build: "./db_mysql"
    ports:
      - "3307:3306"
    volumes:
      - db_data2:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: service_salon
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - salon-network2

  #AUTH SERVICE

  auth2:
    depends_on:
      - mongodb2
    build: "./auth_service"
    environment:
      - browser_url=http://localhost:4040
      - DB_CONN=mongodb://mongodb2:27018/cluster0
    ports:
      - "3010:3000"
    restart: always
    networks:
      - auth-network2

  # SALON SERVICE

  salon2:
    container_name: salon2
    depends_on:
      - mysql2
    build: "./salon_service"
    environment:
      - DB_HOST=mysql2:3307
      - PORT=4020
    ports:
      - "4020:4010"
    restart: always
    networks:
      - salon-network2

  # BROWSER SERVICE

  browser2:
    build: "../browser_service"
    depends_on:
      - auth2
    environment:
      - salon_service_url=http://salon2:4010
      - auth_service_url=http://auth2:3000
    ports:
      - "4040:4030"
    networks:
      - auth-network2
      - salon-network2

  # TRANSPORT SERVICE

  transport:
    build: "../transport_service"
    environment:
      - salon_service_url=http://salon:4020
      - auth_service_url=http://auth:3010
    ports:
      - "5002:5001"
    networks:
      - auth-network2
      - salon-network2

  # FRONT

  front2:
    build: "./car-rental-vue"
    stdin_open: true
    ports:
      - "8082:8081"
    depends_on:
      - auth2
      - salon2
    environment: 
      - VUE_APP_BROWSER_API=http://localhost:4040
      - VUE_APP_SALON_ID=600731da3526f63658f62f3c
      - VUE_APP_AUTH_API=http://localhost:3010
      - VUE_APP_TRANSPORT_API=http://localhost:5002
    networks:
      - auth-network2
      - salon-network2
      

networks:
  auth-network:
    driver: bridge
  salon-network:
    driver: bridge
  auth-network2:
    driver: bridge
  salon-network2:
    driver: bridge
volumes:
  db_data: {}
  data:
  db_data2: {}
  data2:
